services:
  - type: web
    name: laravel-app
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:clear
    startCommand: |
      php artisan migrate --force
      php -S 0.0.0.0:10000 -t public
    phpVersion: 8.2
    buildNixpacks: true
    nixpacksConfigPath: nixpacks.toml
